<script setup lang="ts">
  import type { Collections } from '@nuxt/content'

  const { locale } = useI18n()
  const localePath = useLocalePath()

  const blogCollection = computed(() => `blog_${locale.value}` as keyof Collections)
  const { data: posts } = await useAsyncData(
    'blog',
    () => queryCollection(blogCollection.value).all(),
    { watch: [blogCollection] }
  )

  // post.path is generated by @nuxt/content from the collection's locale prefix
  // (e.g. "/ca/helloworld"), not from the "/blog" page route, so it needs rebuilding.
  const postLink = (post: { path: string }) =>
    localePath(`/blog${post.path.replace(/^\/(ca|it)/, '')}`)
</script>

<template>
  <div>
    <p>list of entries</p>
    <ul>
      <li v-for="post in posts" :key="post.id">
        <NuxtLink :to="postLink(post)">{{ post.title }}</NuxtLink>
      </li>
    </ul>
  </div>
</template>
