<script setup lang="ts">
  const { locale, t } = useI18n()
  const localePath = useLocalePath()

  const blogCollection = computed(() => `blog_${locale.value}` as 'blog_ca' | 'blog_it')
  const { data: posts } = await useAsyncData(
    'blog',
    () => queryCollection(blogCollection.value).all(),
    { watch: [blogCollection] }
  )

  // post.path is generated by @nuxt/content from the collection's locale prefix
  // (e.g. "/ca/helloworld"), not from the "/blog" page route, so it needs rebuilding.
  const postLink = (post: { path: string }) =>
    localePath(`/blog${post.path.replace(/^\/(ca|it)/, '')}`)
</script>

<template>
  <div>
    <p class = 'italic text-sm'>{{ t('blog_list') }}</p>

    <ul>
      <li v-for="post in posts" :key="post.id">
        <NuxtLink
          :to="postLink(post)"
          class="flex justify-between group"
        >
        
        <div>
         <h3 class="font-bold text-xl group-hover:text-coral-500 transition-colors duration-300"> {{ post.title }}</h3>
         <p>{{ post.description }}</p>
        </div>

        <p class="text-sm text-gray-600">{{ formatDate(post.publishedAt, locale) }}</p>
      
      </NuxtLink>
      </li>
    </ul>

  </div>
</template>
